{% set name = "libmodulemd" %}
{% set version = "2.15.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/fedora-modularity/libmodulemd/releases/download/{{ version }}/modulemd-{{ version }}.tar.xz
  sha256: f981ff9f580f19736303e035938e94ad886ecc3cdd8c864c138de9b2e35c7ba3

build:
  number: 0
  skip: true  # [win or osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - pkg-config
    - ninja
  host:
    - python
    - file
    - glib
    - yaml
    - rpm-tools
    - gobject-introspection
    - pygobject
    - meson
    - help2man
  run:
    - python
    - pygobject
    - six
    # https://abi-laboratory.pro/index.php?view=timeline&l=rpm
    - {{ pin_compatible('rpm-tools', max_pin="x.x") }}
    - {{ pin_compatible('file') }}

test:
  commands:
    - modulemd-validator --help

about:
  home: https://github.com/fedora-modularity/libmodulemd
  license: MIT
  license_file: COPYING
  summary: C Library for manipulating module metadata files
  doc_url: https://github.com/fedora-modularity/libmodulemd#libmodulemd
  dev_url: https://github.com/fedora-modularity/libmodulemd

extra:
  recipe-maintainers:
    - chrisburr
